### ISSUE TITLE
Nested directories not supported

### ISSUE THREAD

**Issue by NecatiMeral** [4tecture/Tokenizer#3]
Hi everyone,

when using the tokenizer to apply tokens for a directory structure, it doesn't handle directories well.

My structure consists of the following directories and files:
```
consul/deploy
-> /config
->     /server1.json
->     /server2.json
->     ...
-> docker-compose.yml
```

I want to replace tokens in every file inside the `deploy` directory.
I've tried several ways to achieve this:

## Method 1
```
    - task: Tokenizer@0
      inputs:
        sourcePath: 'consul/deploy/'
        sourceFilesPattern: '**'
        tokenDataSource: 'environmentVariables'
```
Result:
```
Checking for tokens in /azp/agent/_work/20/s/consul/deploy
##[error]EISDIR: illegal operation on a directory, read
```

## Method 2
```
    - task: Tokenizer@0
      inputs:
        sourcePath: 'consul/deploy/'
        sourceFilesPattern: '*.json|*.yml'
        tokenDataSource: 'environmentVariables'
```
Result: 

```
##[warning]No files found for pattern *.json|*.yml
```
